### ISSUE TITLE
Is PHP 8.2 Supported? I get this error after upgrading - Uncaught Error: Undefined constant "ReceiptPrintHq\EscposTools\Parser\Command\STDERR

### ISSUE THREAD

**Issue by smartinsight-at** [receipt-print-hq/escpos-tools#82]
I have just upgraded my PHP to 8.2 and moved to a new server. 

Would anyone be able to confirm that this should working on 8.2 or suggest a way to resolve this error? I just dont want to waste my time if it is not supposed to work.

Many Thanks.

Adam

[03-May-2024 20:31:58 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "ReceiptPrintHq\EscposTools\Parser\Command\STDERR" in /var/www/smartinsight_test/deva/SMART/httpdocs/vendor/escpos-tools/src/Parser/Command/Printout.php:189
Stack trace:
#0 /var/www/smartinsight_test/deva/SMART/httpdocs/vendor/escpos-tools/src/Parser/Command/Printout.php(154): ReceiptPrintHq\EscposTools\Parser\Command\Printout->logUnknownCommand()
#1 /var/www/smartinsight_test/deva/SMART/httpdocs/vendor/escpos-tools/src/Parser/Command/Printout.php(123): ReceiptPrintHq\EscposTools\Parser\Command\Printout->navigateCommand()
#2 /var/www/smartinsight_test/deva/SMART/httpdocs/vendor/escpos-tools/src/Parser/Parser.php(43): ReceiptPrintHq\EscposTools\Parser\Command\Printout->addChar()
#3 /var/www/smartinsight_test/deva/SMART/httpdocs/app/e-shop-pledge-action.php(55): ReceiptPrintHq\EscposTools\Parser\Parser->addString()
#4 /var/www/smartinsight_test/deva/SMART/httpdocs/app/e-shop-pledge-action.php(309): ReceiptToHtml()
#5 {main}
  thrown in /var/www/smartinsight_test/deva/SMART/httpdocs/vendor/escpos-tools/src/Parser/Command/Printout.php on line 189

**Comment by gilbertfl** [comment]
To upgrade to PHP8 there are a few modifications that need to be done to the code.

I have a version that is tested up until PHP8.4. You will find a pull request with my changes.

**Comment by smartinsight-at** [comment]
Thank you, I will dowmload and test it.
